import { launchBrowser, closeBrowser } from "./browser";
import { format } from "date-fns";

/**
 * Generates a professional PDF report for a form submission.
 * @param submission The form submission object with form and data
 * @returns PDF buffer
 */
export async function generateSubmissionPdf(submission: any) {
    const browser = await launchBrowser();
    try {
        const page = await browser.newPage();

        const rows = Object.entries(submission.data)
            .map(([key, value]) => `
                <div style="margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 10px;">
                    <div style="font-size: 10px; font-weight: bold; color: #666; text-transform: uppercase;">${key.replace(/_/g, " ")}</div>
                    <div style="font-size: 14px; color: #000; word-break: break-all;">${value || "-"}</div>
                </div>
            `).join("");

        const html = `
            <html>
                <body style="font-family: sans-serif; padding: 40px; color: #333;">
                    <div style="border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end;">
                        <div>
                            <h1 style="margin: 0; font-size: 24px;">Form Submission Report</h1>
                            <p style="margin: 5px 0 0 0; color: #666;">${submission.form?.name}</p>
                        </div>
                        <div style="text-align: right; font-size: 12px; color: #999;">
                            ID: ${submission.id}<br>
                            Date: ${format(new Date(submission.createdAt), "PPP pp")}
                        </div>
                    </div>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                        ${rows}
                    </div>
                    <div style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; font-size: 10px; color: #ccc; text-align: center;">
                        Generated by Basalt CRM
                    </div>
                </body>
            </html>
        `;

        await page.setContent(html);
        const pdfBuffer = await page.pdf({
            format: "A4",
            margin: { top: "1cm", bottom: "1cm", left: "1cm", right: "1cm" },
            printBackground: true
        });
        return pdfBuffer;
    } finally {
        await closeBrowser(browser);
    }
}
